version: '3'

services:
  drupal:
    image: digdep/drupal-base
    volumes:
      - /path/to/drupal:/var/drupal/www:rw,delegated
    links:
      - db
    ports:
      - "8000:8080"

  db:
    image: mysql:5.5
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
