version: '3'

services:
  drupal:
    image: digdep/drupal-base
    volumes:
      - /path/to/drupal:/projects/drupal/www:rw,delegated
    links:
      - db
    ports:
      - "80:8080"

  db:
    image: mysql:5.5
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "3306:3306"
