version: 2

jobs:
  build:
    docker:
      - image: docker:17-git

    steps:
      - checkout

      - setup_remote_docker:
          version: '17'

      - run: 
          name: Build image
          command: docker build -t drupal .

      - run:
          name: Test web stack
          command: |
            docker run -d --rm --name drupal drupal
            sleep 2
            docker exec drupal curl -s http://localhost:8080/ | grep 'PHP Version'
            docker stop drupal

      - run:
          name: Test Composer
          command: docker run --rm drupal composer -V

      - run:
          name: Test Drush
          command: docker run --rm drupal drush core-status

      - run:
          name: Test Terminus
          command: docker run --rm drupal terminus self:info

      - run:
          name: Push image to Docker Hub
          command: |
            REPO="digdep/drupal-base"
            VERSION_MAJOR="3"
            VERSION_MINOR="1"
            TAG_PREFIX=$([ "$CIRCLE_BRANCH" = "master" ] && echo || echo "${CIRCLE_BRANCH}-")
            TAG_LATEST="$REPO:${TAG_PREFIX}latest"
            TAG_MAJOR="$REPO:${TAG_PREFIX}${VERSION_MAJOR}"
            TAG_MINOR="$REPO:${TAG_PREFIX}${VERSION_MAJOR}.${VERSION_MINOR}"
            docker login -u "$DOCKER_HUB_USERNAME" -p "$DOCKER_HUB_PASSWORD"
            for TAG in "TAG_LATEST" "$TAG_MAJOR" "$TAG_MINOR"; do
              docker tag drupal "$TAG"
              docker push "$TAG"
            done
