version: 2

jobs:
  build:
    docker:
      - image: docker:17.07.0-ce-git

    steps:
      - checkout

      - setup_remote_docker:
          version: 17.07.0-ce

      - run: 
          name: Build image
          command: docker build -t drupal .

      - run:
          name: Test web stack
          command: |
            docker run -d --rm --name drupal drupal
            sleep 2
            docker exec drupal curl -s http://localhost:8080/ | grep 'PHP Version'
            docker stop drupal

      - run:
          name: Test Composer
          command: docker run --rm drupal composer -V

      - run:
          name: Test Drush
          command: docker run --rm drupal drush core-status

      - run:
          name: Push image to Docker Hub
          command: |
            TAG=$([ "$CIRCLE_BRANCH" = "master" ] && echo latest || echo "$CIRCLE_BRANCH")
            docker tag drupal "digdep/drupal-base:$TAG"
            docker login -u "$DOCKER_HUB_USERNAME" -p "$DOCKER_HUB_PASSWORD"
            docker push "digdep/drupal-base:$TAG"
